/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type SessionStatus = { 'submittedForReview' : null } |
  { 'completed' : null } |
  { 'reviewed' : null } |
  { 'inProgress' : null };
export interface SpeakingPrompt {
  'id' : bigint,
  'difficultyLevel' : bigint,
  'title' : string,
  'description' : string,
}
export interface SpeakingSession {
  'startTime' : Time,
  'status' : SessionStatus,
  'studentId' : Principal,
  'endTime' : [] | [Time],
  'recordingUrl' : [] | [string],
  'feedback' : [] | [string],
  'prompt' : SpeakingPrompt,
  'sessionId' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeSession' : ActorMethod<[bigint, string], undefined>,
  'createPrompt' : ActorMethod<[string, string, bigint], bigint>,
  'getAllPrompts' : ActorMethod<[], Array<SpeakingPrompt>>,
  'getAllSessions' : ActorMethod<[], Array<SpeakingSession>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPrompt' : ActorMethod<[bigint], [] | [SpeakingPrompt]>,
  'getSession' : ActorMethod<[bigint], SpeakingSession>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSessions' : ActorMethod<[], Array<SpeakingSession>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reviewSession' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startSession' : ActorMethod<[bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];