/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SpeakingPrompt = IDL.Record({
  'id' : IDL.Nat,
  'difficultyLevel' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const SessionStatus = IDL.Variant({
  'submittedForReview' : IDL.Null,
  'completed' : IDL.Null,
  'reviewed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const SpeakingSession = IDL.Record({
  'startTime' : Time,
  'status' : SessionStatus,
  'studentId' : IDL.Principal,
  'endTime' : IDL.Opt(Time),
  'recordingUrl' : IDL.Opt(IDL.Text),
  'feedback' : IDL.Opt(IDL.Text),
  'prompt' : SpeakingPrompt,
  'sessionId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeSession' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createPrompt' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'getAllPrompts' : IDL.Func([], [IDL.Vec(SpeakingPrompt)], ['query']),
  'getAllSessions' : IDL.Func([], [IDL.Vec(SpeakingSession)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPrompt' : IDL.Func([IDL.Nat], [IDL.Opt(SpeakingPrompt)], ['query']),
  'getSession' : IDL.Func([IDL.Nat], [SpeakingSession], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSessions' : IDL.Func([], [IDL.Vec(SpeakingSession)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reviewSession' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startSession' : IDL.Func([IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SpeakingPrompt = IDL.Record({
    'id' : IDL.Nat,
    'difficultyLevel' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Time = IDL.Int;
  const SessionStatus = IDL.Variant({
    'submittedForReview' : IDL.Null,
    'completed' : IDL.Null,
    'reviewed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const SpeakingSession = IDL.Record({
    'startTime' : Time,
    'status' : SessionStatus,
    'studentId' : IDL.Principal,
    'endTime' : IDL.Opt(Time),
    'recordingUrl' : IDL.Opt(IDL.Text),
    'feedback' : IDL.Opt(IDL.Text),
    'prompt' : SpeakingPrompt,
    'sessionId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeSession' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createPrompt' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'getAllPrompts' : IDL.Func([], [IDL.Vec(SpeakingPrompt)], ['query']),
    'getAllSessions' : IDL.Func([], [IDL.Vec(SpeakingSession)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPrompt' : IDL.Func([IDL.Nat], [IDL.Opt(SpeakingPrompt)], ['query']),
    'getSession' : IDL.Func([IDL.Nat], [SpeakingSession], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSessions' : IDL.Func([], [IDL.Vec(SpeakingSession)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reviewSession' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startSession' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };